### ISSUE TITLE
Is cltorch building and testing applicable for RHEL 7.2?

### ISSUE THREAD

**Issue by streamhsa** [hughperkins/cltorch#78]
Hi,
I need some info about support of this app on RHEL 7.2. Is it supported?
After doing git clone to local setup, I am checking "install.sh". Inside that file, for RHEL OS, compiler and all are not defined so i am getting error "cmake compiler is not found".
Can i get RHEL supported "install.sh" if RHEL is supported and If any handy page which i can follow to build on RHEL 7.2 is nice.

Thanks

**Comment by hughperkins** [comment]
Its supported in the sense that it should probably be possible to make it work, and I'm happy to answer questions about it, but not in the sense that I test on it, or have an RHEL installation available, or personally modify the script to work with RHEL.

 I would think the first steps would be:
- figure out how to install cmake on RHEL 7.2
- install cmake
- figure out how to modify the script to install cmake (this is optional really; you could simply install cmake by hand, then rerun the script)

**Comment by hughperkins** [comment]
(actually, one option could be to use https://github.com/torch/distro to install a non-opencl torch, get that working; then retry the opencl version, using what you've learned from the non-opencl version as a guide)

**Comment by streamhsa** [comment]
Hi,
Somehow i proceed one step further.
I tried "bash install-deps" command on RHEL7.2. It's saying "=>only Ubuntu, ele.OS, Fedora and CentOS distribution supported"
Now, i ignored it and ran "./install.sh". I am getting below error and compilation terminated. I don't know it's due to install-deps command did not work or something else. Full log is attached.

gcc -O2 -fPIC -I/root/torch-cl/install/include -c readline.c -o readline.o
readline.c:7:31: fatal error: readline/readline.h: No such file or directory
 #include <readline/readline.h>
                             ^
c
[torch.zip](https://github.com/hughperkins/cltorch/files/438908/torch.zip)

ompilation terminated.
Error: Build error: Failed compiling object readline.o

**Comment by hughperkins** [comment]
Hi.  Ok cool!  This particular library, I think you can fix with a command something like:
```
yum install readline-devel
```

**Comment by streamhsa** [comment]
Thanks a lot. It resolves building issues and i went one step ahead. :)
I built successfully but still tests are failing with some error.
Below 2 tests are failing, PFA. 
[torch.zip](https://github.com/hughperkins/cltorch/files/439200/torch.zip)
luajit -l torch -e 'torch.test()'
luajit -l nn -e 'nn.test()'

Below 2 are passing:
luajit -l cltorch -e 'cltorch.test()'
luajit -l clnn -e 'clnn.test()'

**Comment by hughperkins** [comment]
Can you give me the full output?  (eg via https://gist.github.com )

**Comment by hughperkins** [comment]
(oh, just noticed the zip file.  Opening :-) )

**Comment by hughperkins** [comment]
```
gels_reuse
 Function call failed
gels : Lapack library not found in compile time
 at /root/torch-cl/pkg/torch/lib/TH/generic/THLapack.c:79
```

Ah, looks like you're missing a BLAS.  Can you somehow install:
- a blas, and
- an lapack
... and then reinstall//rebuild torch/nn, and try again please?

**Comment by streamhsa** [comment]
I have checked already, blas ,openblas and lapack are installed. Still it's failing.
But i am seeing openblas related file not found too while building. Also, some failure observed while building related to QT4 not found but QT4 is also installed on the system.

Errors as below:
-- Checking for [openblas]
--   Library openblas: BLAS_openblas_LIBRARY-NOTFOUND
-- Checking for [openblas - pthread]
--   Library openblas: BLAS_openblas_LIBRARY-NOTFOUND
-- Checking for [goto2 - gfortran]
--   Library goto2: BLAS_goto2_LIBRARY-NOTFOUND
-- Checking for [goto2 - gfortran - pthread]
--   Library goto2: BLAS_goto2_LIBRARY-NOTFOUND
-- Checking for [acml - gfortran]
--   Library acml: BLAS_acml_LIBRARY-NOTFOUND
-- Checking for [Accelerate]
--   Library Accelerate: BLAS_Accelerate_LIBRARY-NOTFOUND
-- Checking for [vecLib]
--   Library vecLib: BLAS_vecLib_LIBRARY-NOTFOUND
-- Checking for [ptf77blas - atlas - gfortran]
--   Library ptf77blas: BLAS_ptf77blas_LIBRARY-NOTFOUND
-- Checking for [blas]
--   Library blas: BLAS_blas_LIBRARY-NOTFOUND
-- Cannot find a library with BLAS API. Not using BLAS.
-- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - pthread - m]

-- Detecting CXX compile features - done
CMake Error at /usr/share/cmake3/Modules/FindQt4.cmake:1326 (message):
  Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x
Call Stack (most recent call first):
  CMakeLists.txt:38 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/root/torch-cl/exe/qtlua/build/CMakeFiles/CMakeOutput.log".
Error: Build error: Failed building.
Error: Failed installing dependency: https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/luacrypto-0.3.2-2.src.rock - Could not find header file for OPENSSL
  No file openssl/evp.h in /usr/local/include
  No file openssl/evp.h in /usr/include
You may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command.
Example: luarocks install luacrypto OPENSSL_DIR=/usr/local

**Comment by streamhsa** [comment]
Package blas-3.4.2-5.el7.x86_64 already installed and latest version
Package openblas-0.2.18-1.el7.x86_64 already installed and latest version
Package 1:qt-4.8.5-11.el7.x86_64 already installed and latest version
Package 1:openssl-1.0.1e-42.el7_1.9.x86_64 already installed and latest version
Package lapack-3.4.2-5.el7.x86_64 already installed and latest version

**Comment by hughperkins** [comment]
Ok.  torch looks for them using the FindBLAS.cmake and FindLAPACK.cmake files, in https://github.com/torch/torch7/tree/master/lib/TH/cmake 

It looks like you *might* be able to prod them into finding your libraries by adding the `.so`s to `CMAKE_LIBRARY_PATH`, https://github.com/torch/distro/blob/master/install.sh#L41

Otherwise, you might want to hack the paths in the Findxxx.cmake files a bit, eg https://github.com/torch/torch7/blob/master/lib/TH/cmake/FindBLAS.cmake#L70

**Comment by hughperkins** [comment]
(to be honest, if the cltorch and clnn tests are all passing, you could just jump straight to trying whatever it is you want to try, and ignore the non-gpu blas errors.  I assume from your name, and your github followers/followees that you are AMD?  So, I guess you mostly want to jump straight into looking at convolution perhaps?  This should work just fine without non-gpu blas installed)

**Comment by hughperkins** [comment]
(by the way, qt is not required, unless you want to start using jupyter-type notebooks, and other gui things)

**Comment by streamhsa** [comment]
Thanks a lot for the quick help. We can close this thread.

**Comment by hughperkins** [comment]
Cool :-)  Let me know if you have any questions.
